/*
 * RECREATIONMS_coingeckoApi
 * this is an api to test the skill of the RecreationMS programming department
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RecreationmsCoingeckoApi) {
      root.RecreationmsCoingeckoApi = {};
    }
    root.RecreationmsCoingeckoApi.Symbol = factory(root.RecreationmsCoingeckoApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Symbol model module.
   * @module model/Symbol
   * @version 1.0.2
   */

  /**
   * Constructs a new <code>Symbol</code>.
   * @alias module:model/Symbol
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Symbol</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Symbol} obj Optional instance to populate.
   * @return {module:model/Symbol} The populated <code>Symbol</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;


  return exports;

}));
