/*
 * RECREATIONMS_coingeckoApi
 * this is an api to test the skill of the RecreationMS programming department
 *
 * OpenAPI spec version: 1.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Coins', 'model/Symbol', 'api/CoinsApi', 'api/PingApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Coins'), require('./model/Symbol'), require('./api/CoinsApi'), require('./api/PingApi'));
  }
}(function(ApiClient, Coins, Symbol, CoinsApi, PingApi) {
  'use strict';

  /**
   * this_is_an_api_to_test_the_skill_of_the_RecreationMS_programming_department.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var RecreationmsCoingeckoApi = require('index'); // See note below*.
   * var xxxSvc = new RecreationmsCoingeckoApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new RecreationmsCoingeckoApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new RecreationmsCoingeckoApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new RecreationmsCoingeckoApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.2
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Coins model constructor.
     * @property {module:model/Coins}
     */
    Coins: Coins,
    /**
     * The Symbol model constructor.
     * @property {module:model/Symbol}
     */
    Symbol: Symbol,
    /**
     * The CoinsApi service constructor.
     * @property {module:api/CoinsApi}
     */
    CoinsApi: CoinsApi,
    /**
     * The PingApi service constructor.
     * @property {module:api/PingApi}
     */
    PingApi: PingApi
  };

  return exports;
}));
